kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fiotest-pv-claim
spec:
  storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
